### ISSUE TITLE
新增拖动功能

### ISSUE THREAD

**Issue by guan5444** [KarlKaijie/SiYuanToDo#11]
希望增加拖动功能，方便进行同一List内（比如未完成）优先级的手动排序，以及跨List拖动变更，谢谢！

**Comment by BaireMe** [comment]
同样的，希望有快速快速完成的功能。现在的任务完成得流程是：点击项→选择任务状态→选择已完成→点击提交。太过繁琐了，希望有拖拽完成或者是齿轮下方直接有修改为完成得功能。

**Comment by KarlKaijie** [comment]
v0.1.8
