### ISSUE TITLE
数据持久化方案改进建议

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [KarlKaijie/SiYuanToDo#2]
目前持久化的数据会保存在笔记本目录下的 `cachetask` 目录中, 在挂件中无法删除, 且可能在未来会思源内核被视为无效文件删除, 下面有两个替代方案

1. 将 `JSON 字符串` / `base64 编码后的 JSON 字符串` 保存在挂件块自定义属性中(例如 `custom-data`), 可以使用 API `/api/attr/getBlockAttrs` 与 `/api/attr/setBlockAttrs` 读写块属性
   - 该方案在删除挂件块时可以同时删除持久化的数据
2. 将 `*.json` 文件使用 API `/api/asset/upload` 或者 `/api/file/putFile` 保存在 `/assets/` 目录下, 然后将该文件引用路径保存在块属性 `custom-data-assets` 中, 这样就不会被思源内核视为未引用文件删除了
   - 该方案在删除挂件块时将持久化数据文件视为未引用文件, 交由思源内核清理

**Comment by KarlKaijie** [comment]
> 目前持久化的数据会保存在笔记本目录下的 `cachetask` 目录中, 在挂件中无法删除, 且可能在未来会思源内核被视为无效文件删除, 下面有两个替代方案
> 
> 1. 将 `JSON 字符串` / `base64 编码后的 JSON 字符串` 保存在挂件块自定义属性中(例如 `custom-data`), 可以使用 API `/api/attr/getBlockAttrs` 与 `/api/attr/setBlockAttrs` 读写块属性
> 
> * 该方案在删除挂件块时可以同时删除持久化的数据
> 
> 2. 将 `*.json` 文件使用 API `/api/asset/upload` 或者 `/api/file/putFile` 保存在 `/assets/` 目录下, 然后将该文件引用路径保存在块属性 `custom-data-assets` 中, 这样就不会被思源内核视为未引用文件删除了
> 
> * 该方案在删除挂件块时将持久化数据文件视为未引用文件, 交由思源内核清理

感谢您提的方案。方案2确认下了可行。 方案1的话，不知自定义属性是否有长度限制呢？
