### ISSUE TITLE
添加多个 Todo 时，数据能否分开

### ISSUE THREAD

**Issue by RogerHuHu** [KarlKaijie/SiYuanToDo#3]
目前我添加多份 Todo 时，数据是一样的，能否分开，因为会存在不同类别的 Todo，比如工作、生活、旅行等

**Comment by KarlKaijie** [comment]
> 目前我添加多份 Todo 时，数据是一样的，能否分开，因为会存在不同类别的 Todo，比如工作、生活、旅行等

是指同一个文档里，建多个看板的挂件吗？  如果是的话，请在仓库下载最新的0.0.7版本， 或者思源市场的0.0.6版本，待明天更新0.0.7版本，0.0.6版本请勿删除思源资源里的路径为widget_tasklist_database的未引用资源，该问题在0.0.7版本已修复。
